
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohamedan_Farag
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
     int count_turn=0;
     
     int count_p1=0;
     
     int count_p2=0;
      
     String x_or_o ="xo";
     
     boolean game_is_over=false;
      
     int is_visited[]={0,0,0,0,0,0,0,0,0,0};
     
     int [][]board = new int [4][4];
     
     int who_win(){
         
         boolean p1=false; boolean p2=false;
         
        for(int i=0;i<3;i++){
             
           if((board[i][0]==board[i][1])&& (board[i][2]==board[i][1])){
              if(board[i][0]!=0 && board[i][1]!=0 && board[i][2]!=0) {
                  
                if(board[i][0]==1)p1=true;
                
               else p2=true;
                
              }
      
           }
           
           if( (board[0][i]==board[1][i])  && (board[2][i]==board[1][i])){
                if(board[0][i]!=0 && board[1][i]!=0 && board[2][i]!=0){
                if(board[0][i]==1)p1=true;
                    else p2=true;
                
                }
           }
           
        }
        
       if( (board[0][0]==board[1][1])  && (board[2][2]==board[1][1])){
           if(board[0][0]!=0 && board[1][1]!=0 && board[2][2]!=0){
            if(board[1][1]==1)p1=true;
                    else p2=true;
           }
           
       }
       
            if( (board[0][2]==board[1][1])  && (board[2][0]==board[1][1])){
           if(board[0][2]!=0 && board[1][1]!=0 && board[2][0]!=0)
            if(board[1][1]==1)p1=true;
                    else p2=true;
                
           
       }
        
        if(p1)return 1;
        
         if(p2)return 2;
        
         return 0;
         
     }
     

     
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        b8 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        jPanel1.setBackground(new java.awt.Color(153, 5, 56));

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jLabel1.setFont(new java.awt.Font("Ink Free", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TIC_TAC_TOE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 5, 23));

        b8.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b0.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        b0.setForeground(new java.awt.Color(0, 0, 0));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton1.setText("PLAY AGAIN ˗ˏˋ ★ ˎˊ˗");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Console", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mohamedan_Farag\\Desktop\\TIC_TAC_TOE\\TICTACTOE\\ICONS\\o (1).png")); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Console", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLAYER 2");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Console", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mohamedan_Farag\\Desktop\\TIC_TAC_TOE\\TICTACTOE\\ICONS\\close (1).png")); // NOI18N
        jLabel4.setText("PLAYER 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton1)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     
    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
          if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
        
        if(is_visited[0]==0){
            is_visited[0]=1;
             if(count_turn%2==0){
                 b0.setText("x");
                 board[0][0]=1;
                }
             else {
               b0.setText("0"); 
               board[0][0]=2;
             }
             count_turn++;
             
              int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
            game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
            game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
          if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
        
         if(is_visited[1]==0){
            is_visited[1]=1;
             if(count_turn%2==0){
                 b1.setText("x");
                 board[0][1]=1;
                }
             else {
               b1.setText("0"); 
               board[0][1]=2;
             }
             count_turn++;
               int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
           game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
           game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
          if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
        
        if(is_visited[2]==0){
            is_visited[2]=1;
             if(count_turn%2==0){
                 b2.setText("x");
                 board[0][2]=1;
                }
             else {
               b2.setText("0"); 
               board[0][2]=2;
             }
             count_turn++;
               int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
            game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
            game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
          if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
        
        if(is_visited[3]==0){
            is_visited[3]=1;
             if(count_turn%2==0){
                 b3.setText("x");
                 board[1][0]=1;
                }
             else {
               b3.setText("0"); 
               board[1][0]=2;
             }
             count_turn++;
               int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
            game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
           game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
          if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
        
        if(is_visited[4]==0){
            is_visited[4]=1;
             if(count_turn%2==0){
                 b4.setText("x");
                 board[1][1]=1;
                }
             else {
               b4.setText("0"); 
               board[1][1]=2;
             }
             count_turn++;
               int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
            game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
            game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
         if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
        
         if(is_visited[5]==0){
            is_visited[5]=1;
             if(count_turn%2==0){
                 b5.setText("x");
                 board[1][2]=1;
                }
             else {
               b5.setText("0"); 
               board[1][2]=2;
             }
             count_turn++;
               int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
           game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
            game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
         if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
        
         if(is_visited[6]==0){
            is_visited[6]=1;
             if(count_turn%2==0){
                 b6.setText("x");
                 board[2][0]=1;
                }
             else {
               b6.setText("0"); 
               board[2][0]=2;
             }
             count_turn++;
               int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
           game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
            game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
         if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
        
          if(is_visited[7]==0){
            is_visited[7]=1;
             if(count_turn%2==0){
                 b7.setText("x");
                 board[2][1]=1;
                }
             else {
               b7.setText("0"); 
               board[2][1]=2;
             }
             count_turn++;
             
               int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
           game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
           game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if(game_is_over){
            JOptionPane.showMessageDialog(rootPane,"GAME IS OVER !");
        }
        else 
          if(is_visited[8]==0){
            is_visited[8]=1;
             if(count_turn%2==0){
                 b8.setText("x");
                 board[2][2]=1;
                }
             else {
               b8.setText("0"); 
               board[2][2]=2;
             }
             count_turn++;
             
               int result= who_win();
              
              if(result==1){
            JOptionPane.showMessageDialog(rootPane,"Player One Win ! "); 
            game_is_over=true;
              }
              else if(result==2){
                  JOptionPane.showMessageDialog(rootPane,"Player Two Win ! "); 
            game_is_over=true;
              }
              else if(count_turn==9){
                  JOptionPane.showMessageDialog(rootPane,"NO ONE WIN ! ");
                  game_is_over=true;
              }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose another Bottom !");  
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // To restart the game 
        
        count_turn=0;
        
        game_is_over=false;
        
        for(int i=0;i<3;i++){
            for(int j=0;j<3;j++){
                board[i][j]=0;
            }
        }
        
        for(int i=0;i<9;i++){
            is_visited[i]=0;
        }
        
        b0.setText(""); 
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
